import type { CasaProperty, ExternalProperty } from './types';

export const casaProperties: CasaProperty[] = [
  {
    source: 'casa', id: 'c1', title: 'Modern Studio in Mitte', type: 'studio',
    city: 'Berlin', address: 'Rosenthaler Str. 12, Mitte', price: 750,
    bedrooms: 1, size: 32, availableFrom: '2026-06-01',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Bright studio in the heart of Berlin Mitte. Fully furnished with high-speed WiFi and all bills included. Walking distance to U-Bahn and local amenities.',
    featured: true,
  },
  {
    source: 'casa', id: 'c2', title: 'Spacious 2-Room Flat – Kreuzberg', type: 'apartment',
    city: 'Berlin', address: 'Bergmannstr. 45, Kreuzberg', price: 1100,
    bedrooms: 2, size: 58, availableFrom: '2026-05-15',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    features: ['furnished', 'balcony', 'wifi'],
    description: 'Charming 2-room flat in vibrant Kreuzberg. Features a private balcony, fully furnished, and located 5 minutes from Mehringdamm U-Bahn.',
    featured: true,
  },
  {
    source: 'casa', id: 'c3', title: 'Cosy Room in Shared Flat – Prenzlauer Berg', type: 'room',
    city: 'Berlin', address: 'Stargarder Str. 7, Prenzlauer Berg', price: 620,
    bedrooms: 1, size: 18, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Private room in a friendly 3-person shared flat. All utilities included, furnished, in one of Berlin\'s most popular neighbourhoods.',
  },
  {
    source: 'casa', id: 'c4', title: 'Studio near TU Munich', type: 'studio',
    city: 'Munich', address: 'Arcisstr. 55, Maxvorstadt', price: 950,
    bedrooms: 1, size: 28, availableFrom: '2026-07-01',
    images: ['https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800'],
    features: ['furnished', 'wifi', 'parking'],
    description: 'Compact studio 5 minutes walk from TU Munich campus. Includes parking space and high-speed internet.',
    featured: true,
  },
  {
    source: 'casa', id: 'c5', title: '3-Room Apartment – Schwabing', type: 'apartment',
    city: 'Munich', address: 'Leopoldstr. 112, Schwabing', price: 1800,
    bedrooms: 3, size: 85, availableFrom: '2026-06-15',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800'],
    features: ['furnished', 'balcony', 'parking', 'bills'],
    description: 'Elegant 3-room apartment in prestigious Schwabing. Large balcony, underground parking, and all bills included.',
  },
  {
    source: 'casa', id: 'c6', title: 'Private Room – Maxvorstadt', type: 'room',
    city: 'Munich', address: 'Türkenstr. 23, Maxvorstadt', price: 720,
    bedrooms: 1, size: 20, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Sunny private room near LMU and art museums. Bills and WiFi included in a quiet, well-maintained building.',
  },
  {
    source: 'casa', id: 'c7', title: 'Modern Studio – Altona', type: 'studio',
    city: 'Hamburg', address: 'Ottenser Hauptstr. 18, Altona', price: 820,
    bedrooms: 1, size: 35, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['furnished', 'wifi', 'balcony'],
    description: 'Stylish studio in Altona with a private balcony. Recently renovated, 3 min from Altona S-Bahn station.',
    featured: true,
  },
  {
    source: 'casa', id: 'c8', title: '2-Room Flat – Eimsbüttel', type: 'apartment',
    city: 'Hamburg', address: 'Osterstr. 67, Eimsbüttel', price: 1150,
    bedrooms: 2, size: 55, availableFrom: '2026-05-20',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Light-filled 2-room flat in the popular Eimsbüttel neighbourhood. All bills included, 10 min to city centre.',
  },
  {
    source: 'casa', id: 'c9', title: 'Room in Student House – Barmbek', type: 'shared',
    city: 'Hamburg', address: 'Fuhlsbüttler Str. 201, Barmbek', price: 550,
    bedrooms: 1, size: 16, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Affordable shared room in a 5-person student house. Communal kitchen and living area, all bills included.',
  },
  {
    source: 'casa', id: 'c10', title: 'Studio – Sachsenhausen', type: 'studio',
    city: 'Frankfurt', address: 'Schweizer Str. 34, Sachsenhausen', price: 880,
    bedrooms: 1, size: 30, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800'],
    features: ['furnished', 'wifi'],
    description: 'Neat studio in Frankfurt Sachsenhausen, close to the Apple Juice quarter and 15 min from Goethe University.',
  },
  {
    source: 'casa', id: 'c11', title: '2-Room Apartment – Bornheim', type: 'apartment',
    city: 'Frankfurt', address: 'Berger Str. 145, Bornheim', price: 1250,
    bedrooms: 2, size: 60, availableFrom: '2026-07-01',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    features: ['furnished', 'balcony', 'wifi', 'parking'],
    description: 'Well-appointed 2-room apartment in lively Bornheim. Balcony, parking space, and close to tram lines.',
    featured: true,
  },
  {
    source: 'casa', id: 'c12', title: 'Private Room – Nordend', type: 'room',
    city: 'Frankfurt', address: 'Glauburgstr. 8, Nordend', price: 690,
    bedrooms: 1, size: 19, availableFrom: '2026-05-15',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Comfortable private room in a shared flat in upmarket Nordend. All bills covered, friendly flatmates.',
  },
  {
    source: 'casa', id: 'c13', title: 'Studio – Ehrenfeld', type: 'studio',
    city: 'Cologne', address: 'Venloer Str. 234, Ehrenfeld', price: 780,
    bedrooms: 1, size: 31, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['furnished', 'wifi'],
    description: 'Trendy studio in Cologne\'s creative Ehrenfeld district. Close to bars, restaurants, and the S-Bahn.',
  },
  {
    source: 'casa', id: 'c14', title: '3-Room Flat – Südstadt', type: 'apartment',
    city: 'Cologne', address: 'Bonner Str. 67, Südstadt', price: 1450,
    bedrooms: 3, size: 78, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800'],
    features: ['furnished', 'balcony', 'wifi', 'bills', 'parking'],
    description: 'Spacious 3-room flat with balcony in Cologne Südstadt. Everything included — perfect for 2-3 students sharing.',
    featured: true,
  },
  {
    source: 'casa', id: 'c15', title: 'Room – Nippes', type: 'room',
    city: 'Cologne', address: 'Neusser Str. 102, Nippes', price: 590,
    bedrooms: 1, size: 17, availableFrom: '2026-05-15',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Bright private room in up-and-coming Nippes neighbourhood. Tram stop 2 minutes away.',
  },
  {
    source: 'casa', id: 'c16', title: 'Studio – Stuttgart Mitte', type: 'studio',
    city: 'Stuttgart', address: 'Tübinger Str. 12, Mitte', price: 860,
    bedrooms: 1, size: 29, availableFrom: '2026-06-15',
    images: ['https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800'],
    features: ['furnished', 'wifi', 'parking'],
    description: 'Central studio in Stuttgart with parking space. 10 minutes to Stuttgart University by U-Bahn.',
  },
  {
    source: 'casa', id: 'c17', title: '2-Room Flat – Stuttgart West', type: 'apartment',
    city: 'Stuttgart', address: 'Rotebühlstr. 89, West', price: 1150,
    bedrooms: 2, size: 52, availableFrom: '2026-07-01',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    features: ['furnished', 'wifi', 'balcony'],
    description: '2-room flat with lovely balcony in Stuttgart West. Great transport links to the university and city centre.',
  },
  {
    source: 'casa', id: 'c18', title: 'Private Room – Düsseldorf Bilk', type: 'room',
    city: 'Dusseldorf', address: 'Bilker Allee 78, Bilk', price: 650,
    bedrooms: 1, size: 20, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Sunny private room near HHU Düsseldorf campus. All utilities included, 5 min to the metro.',
  },
  {
    source: 'casa', id: 'c19', title: 'Studio – Düsseldorf Flingern', type: 'studio',
    city: 'Dusseldorf', address: 'Ackerstr. 23, Flingern', price: 820,
    bedrooms: 1, size: 33, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['furnished', 'wifi'],
    description: 'Stylish studio in Flingern, Düsseldorf\'s hipster neighbourhood. Newly renovated with modern finishes.',
    featured: true,
  },
  {
    source: 'casa', id: 'c20', title: '2-Room Flat – Düsseldorf Pempelfort', type: 'apartment',
    city: 'Dusseldorf', address: 'Nordstr. 34, Pempelfort', price: 1200,
    bedrooms: 2, size: 57, availableFrom: '2026-05-20',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    features: ['furnished', 'balcony', 'wifi', 'bills'],
    description: 'Elegant 2-room flat with balcony close to the Rhine. All bills included, quiet residential street.',
  },
  {
    source: 'casa', id: 'c21', title: 'Studio – Leipzig Südvorstadt', type: 'studio',
    city: 'Leipzig', address: 'Karl-Liebknecht-Str. 45, Südvorstadt', price: 580,
    bedrooms: 1, size: 28, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Affordable studio in Leipzig\'s student heartland. Bills included, surrounded by cafés and bars.',
    featured: true,
  },
  {
    source: 'casa', id: 'c22', title: '2-Room Flat – Leipzig Gohlis', type: 'apartment',
    city: 'Leipzig', address: 'Menckestr. 12, Gohlis', price: 780,
    bedrooms: 2, size: 55, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    features: ['furnished', 'wifi', 'balcony'],
    description: 'Charming 2-room flat in quiet Gohlis. Balcony, furnished, close to Clara-Zetkin-Park and tram stops.',
  },
  {
    source: 'casa', id: 'c23', title: 'Room – Leipzig Connewitz', type: 'room',
    city: 'Leipzig', address: 'Wolfgang-Heinze-Str. 8, Connewitz', price: 450,
    bedrooms: 1, size: 16, availableFrom: '2026-05-15',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Budget-friendly room in lively Connewitz. Perfect for students who want to be in the middle of the action.',
  },
  {
    source: 'casa', id: 'c24', title: 'Studio – Dresden Neustadt', type: 'studio',
    city: 'Dresden', address: 'Alaunstr. 67, Neustadt', price: 620,
    bedrooms: 1, size: 30, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['furnished', 'wifi'],
    description: 'Cosy studio in Dresden\'s artistic Neustadt district. 5 min from TU Dresden and the city\'s best nightlife.',
  },
  {
    source: 'casa', id: 'c25', title: '2-Room Flat – Dresden Striesen', type: 'apartment',
    city: 'Dresden', address: 'Schandauer Str. 23, Striesen', price: 850,
    bedrooms: 2, size: 52, availableFrom: '2026-07-01',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    features: ['furnished', 'wifi', 'balcony', 'parking'],
    description: '2-room flat in calm Striesen with balcony and parking. 15 min tram ride to TU Dresden.',
    featured: true,
  },
  {
    source: 'casa', id: 'c26', title: 'Studio – Nuremberg Gostenhof', type: 'studio',
    city: 'Nuremberg', address: 'Gostenhofer Hauptstr. 34, Gostenhof', price: 680,
    bedrooms: 1, size: 27, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Studio in Nuremberg\'s up-and-coming Gostenhof area. All bills included, 10 min to FAU campus.',
  },
  {
    source: 'casa', id: 'c27', title: '3-Room Flat – Nuremberg Südstadt', type: 'apartment',
    city: 'Nuremberg', address: 'Südstadtpark 5, Südstadt', price: 1200,
    bedrooms: 3, size: 75, availableFrom: '2026-06-15',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800'],
    features: ['furnished', 'balcony', 'wifi', 'parking', 'bills'],
    description: 'Large 3-room flat with balcony and parking near Südstadtpark. Ideal for students sharing.',
  },
  {
    source: 'casa', id: 'c28', title: 'Room – Nuremberg Langwasser', type: 'room',
    city: 'Nuremberg', address: 'Brunecker Str. 12, Langwasser', price: 500,
    bedrooms: 1, size: 18, availableFrom: '2026-05-15',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Affordable private room with all bills included. Direct metro to FAU and city centre.',
  },
  {
    source: 'casa', id: 'c29', title: 'Studio – Berlin Friedrichshain', type: 'studio',
    city: 'Berlin', address: 'Warschauer Str. 56, Friedrichshain', price: 820,
    bedrooms: 1, size: 34, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    features: ['furnished', 'wifi', 'balcony'],
    description: 'Vibrant studio near East Side Gallery. Private balcony, fully furnished, 2 min from Warschauer Str. station.',
    featured: true,
  },
  {
    source: 'casa', id: 'c30', title: 'Apartment – Munich Neuhausen', type: 'apartment',
    city: 'Munich', address: 'Nymphenburger Str. 34, Neuhausen', price: 1600,
    bedrooms: 2, size: 65, availableFrom: '2026-06-01',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    features: ['furnished', 'wifi', 'parking', 'bills'],
    description: 'Premium 2-room apartment near Nymphenburg Palace. Parking, all bills, and close to LMU via tram.',
  },
  {
    source: 'casa', id: 'c31', title: 'Shared Room – Berlin Neukölln', type: 'shared',
    city: 'Berlin', address: 'Sonnenallee 23, Neukölln', price: 480,
    bedrooms: 1, size: 14, availableFrom: '2026-05-01',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800'],
    features: ['furnished', 'wifi', 'bills'],
    description: 'Budget shared room in vibrant Neukölln. All bills included, international community of students.',
  },
];

export const externalProperties: ExternalProperty[] = [
  {
    source: 'housinganywhere', id: 'h1', title: 'Bright Studio – Berlin Mitte',
    type: 'studio', city: 'Berlin', address: 'Berlin Mitte', price: 890,
    bedrooms: 1, size: 30, availableFrom: '2026-06-01',
    image: 'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800',
    features: ['furnished', 'wifi'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h2', title: '2-Room Flat – Munich Schwabing',
    type: 'apartment', city: 'Munich', address: 'Munich Schwabing', price: 1400,
    bedrooms: 2, size: 60, availableFrom: '2026-07-01',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    features: ['furnished', 'balcony'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h3', title: 'Student Room – Hamburg Altona',
    type: 'room', city: 'Hamburg', address: 'Hamburg Altona', price: 600,
    bedrooms: 1, size: 18, availableFrom: '2026-05-15',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
    features: ['furnished', 'bills', 'wifi'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h4', title: 'Modern Studio – Frankfurt City',
    type: 'studio', city: 'Frankfurt', address: 'Frankfurt Innenstadt', price: 950,
    bedrooms: 1, size: 33, availableFrom: '2026-06-15',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    features: ['furnished', 'wifi', 'parking'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h5', title: 'Cosy Room – Cologne Ehrenfeld',
    type: 'room', city: 'Cologne', address: 'Cologne Ehrenfeld', price: 560,
    bedrooms: 1, size: 17, availableFrom: '2026-05-01',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
    features: ['furnished', 'wifi', 'bills'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h6', title: '3-Room Apartment – Berlin Prenzlauer Berg',
    type: 'apartment', city: 'Berlin', address: 'Berlin Prenzlauer Berg', price: 1650,
    bedrooms: 3, size: 80, availableFrom: '2026-07-15',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    features: ['furnished', 'balcony', 'wifi'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h7', title: 'Studio – Munich Maxvorstadt',
    type: 'studio', city: 'Munich', address: 'Munich Maxvorstadt', price: 1050,
    bedrooms: 1, size: 29, availableFrom: '2026-06-01',
    image: 'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800',
    features: ['furnished', 'wifi'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h8', title: 'Shared Flat Room – Leipzig Südvorstadt',
    type: 'shared', city: 'Leipzig', address: 'Leipzig Südvorstadt', price: 400,
    bedrooms: 1, size: 15, availableFrom: '2026-05-01',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
    features: ['furnished', 'wifi', 'bills'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h9', title: 'Modern 2-Room – Hamburg Eimsbüttel',
    type: 'apartment', city: 'Hamburg', address: 'Hamburg Eimsbüttel', price: 1200,
    bedrooms: 2, size: 54, availableFrom: '2026-06-01',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    features: ['furnished', 'wifi', 'balcony'],
    externalUrl: 'https://housinganywhere.com',
  },
  {
    source: 'housinganywhere', id: 'h10', title: 'Studio – Stuttgart Mitte',
    type: 'studio', city: 'Stuttgart', address: 'Stuttgart Mitte', price: 820,
    bedrooms: 1, size: 28, availableFrom: '2026-07-01',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    features: ['furnished', 'wifi'],
    externalUrl: 'https://housinganywhere.com',
  },
];

export const allProperties = [...casaProperties, ...externalProperties];
